name: Check Artifact Existence
description: Check it
# description from  https://github.com/actions/download-artifact/blob/c4c6db724f9510b2b3cff5ebcc417c87a2b2fa97/action.yml
inputs:
  name:
    description: 'Name of the artifact to check'
    required: true
outputs:
  exists:
    description: Determines if the artifact with the provided name is present.
runs:
  using: "composite"
  steps:
    - name: generate random directory
      shell: bash
      run: echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
      id: gen-random
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: "${{ steps.gen-random.outputs.random_number }}/"
      continue-on-error: true
      id: artifact-download
    - run: |
        rm -rf ${{ steps.gen-random.outputs.random_number }}/
      shell: bash
      if: ${{ steps.artifact-download.outcome == 'success' }}
    - run: |
       echo "exists=${{steps.artifact-download.outcome}}" >> $GITHUB_OUTPUT
      shell: bash
      if: ${{ steps.artifact-download.outcome == 'success' || steps.artifact-download.outcome == 'failure'}}
