# LICENSE: LGPL-3.0-or-later
name: "Reusable workflow that tests whether the check artifact works when called from another workflow"

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: the artifact name to be checked for

jobs:
  sets_false_on_missing:
    name: Sets false when no artifact for the name exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: 'missing-dependency'
        id: "existence-check"
      - name: Fail when expected output isn't set
        run: |
          exit 1
        if: ${{ steps.existence-check.outputs.exists != 'false' }}
  sets_true_when_there:
    name: Sets true when artifact for the name exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: ${{inputs.name}}
        id: "existence-check"
      - name: Fail when expected output isn't set
        run: |
          exit 1
        if: ${{ steps.existence-check.outputs.exists != 'true' }}
      