name: "test"
on:
  workflow_dispatch:
  push:
  

    

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: "something"
        

      
