name: "test"
on:
  workflow_dispatch:
    

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "who-knows"
          path: random-path
        id: "download-artifact-result"
        continue-on-error: true
      - run: |
          echo "${{ toJSON(steps.download-artifact-result) }}"

      
