# LICENSE: LGPL-3.0-or-later
name: "CI Test for Github Action"
on:
  workflow_dispatch:
  push:

jobs:
  sets_false_on_missing:
    name: Sets false when no artifact for the name exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: "missing-artifact"
        id: "existence-check"
      - name: Fail when expected output isn't set
        run: |
          exit 1
        if: ${{ steps.existence-check.outputs.exists != 'false' }}
  sets_true_when_there:
    name: Sets true when artifact for the name exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: "artifact-that-exists"
          path: action.yml
      - uses: ./
        with:
          name: "artifact-that-exists"
        id: "existence-check"
      - name: Fail when expected output isn't set
        run: |
          exit 1
        if: ${{ steps.existence-check.outputs.exists != 'true' }}

  test_via_reusable_workflow:
    name: "Test checking when using a reusable workflow"
    needs: [sets_true_when_there]
    uses: './.github/workflows/reusable-workflow.yml'
    with:
      name: 'artifact-that-exists'
  
        
        

      
