name: "test"
on:
  workflow_dispatch:
  push:

jobs:
  sets_false_on_missing:
    name: Sets false when no artifact for the name exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: "missing-artifact"
        id: "existence-check"
      - run: |
          exit 1
        if: ${{ steps.existence-check.outputs.exists != 'false' }}
  sets_true_when_there:
    name: Sets true when no artifact for the name exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: "artifact-that-exists"
          path: action.yml
      - uses: ./
        with:
          name: "artifact-that-exists"
        id: "existence-check"
      - run: |
          exit 1
        if: ${{ steps.existence-check.outputs.exists == 'true' }}
        
        

      
