name: "test"
on:
  workflow_dispatch:
  push:

jobs:
  sets_failure_on_missing:
    name: Sets failure when no artifact for the name exists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          name: "missing-artifact"
        id: "existence-check"
      - run: |
          exit 1
        if: ${{ steps.existence-check.outputs.exists != false }}
        
        

      
